---
title: "Charlesworth on birth and death"
author: "Bruce Kendall"
date: "10/14/2019"
output: pdf_document
---

Charlesworth (1980; all page and equation references to the 1st edition) does not dwell on differences in selection on annual birth rate vs. annual death rate, but there are hints. 
Here I try to trace things out, focusing on the discrete age-class models.

# Demographic definitions (chapter 1)
Discrete time:

* $m(x, t)$ is the number of female zygotes produced by a female aged $x$ in year $t$ (p. 4)
* $P(x,t)$ is the probability that a female of age $x$ at the start of the breeding season in year $t$ survives the subsequent year (p. 3)
* The quantity $f(x,t) = m(x,t) P(0,t)$ is named the "net fecundity" (p. 5, eq. 1.3). This is what Caswell calls the "fertility coefficient"
* Eq. (1.3) indicates that his models are what we would now call *prebreeding census models*, with the youngest age class being age 1.
* $l(x,t)$ is the "probability that a female survives from conception in year $t-x$ to age $x$ at the beginning of the breeding season in year $t$" (p. 10). It is defined as $l(x,t) = \prod_{y=1}^x P(x-y, t-y)$ (eq. 1.15). This is the "survival function"; note that $t$ indexes the *current* year, not the year that the cohort was born.
* $k(x,t)$, is "the net expectation of female offspring at age $x$, attributable to a female born at time $t-x$" (p. 10). It is called the "reproductive function," given as $k(x,t) = l(x,t) m(x,t)$ (eq. 1.16)

Continuous time:

* $m(x, t)$ is the rate of production of female zygotes  by a female aged $x$ at time $t$ (p. 13)
* $\mu(x,t)$ is the age-specific death rate at time $t$ (p. 12)
* $l(x,t)$ is the "probability that a female survives from conception at time $t-x$ to age $x$ at time $t$" (p. 12). Called the "survival function," it is given by $l(x,t) = \exp\left[- \int_0^x \mu(y, t-y) dy \right]$ (eq. 1.22).
* $k(x,t)$, is the "reproductive function," given as $k(x,t) = l(x,t) m(x,t)$ (p. 13)

Throughout the book, Charlesworth distinguishes between males and females; analagous demographic parameters (and derived quantities) for males are indicated with an asterisk.

The remainder of chapter 1 is devoted to the dynamics of the age-structured models, under various assumptions about time-dependence and density-dependence in the parameters.

# Genetic definitions (chapter 2)
* $A_i$ is the $i$'th allele at a locus. There are $m$ total alleles (p. 72)
* $A_i A_j$ is a genotype of an individual at the locus, with $A_i$ coming from the mother and $A_j$ from the father (p. 72)
* $p_{ij}(x, t)$ is the frequency of genotype $A_i A_j$ among age-$x$ females at time $t$. $\textbf{p}_{ij}(t)$ denotes the vector across ages (p. 72)
* $p_{i}(x, t)$ is the frequency of allele $A_i$ among age-$x$ females at time $t$. $\textbf{p}_{i}(t)$ denotes the vector across ages (p. 72)
* $n_{ij}(x, t)$ is the numbers of age-$x$ females with genotype $A_i A_j$ at time $t$. Corresponding vectors are given by $\textbf{n}_{ij}(t)$  (p. 72)
* $n_{i}(x, t)$ are the numbers of copies of allele $i$ carried by age-$x$ females at time $t$. Corresponding vectors are given by $\textbf{n}_{i}(t)$ (p. 72)

Again, corresponding quantities for males are indicated with an asterisk.

The remainder of chapter 2 derives various results (conditions for Hardy-Weinburg equilibria, drift, sex-linked alleles) when the allele does not affect fitness.

# Genetic equilibria under selection (chapter 3)
Now the survival and/or birth rates depend on the genotype, so that we now have $m_{ij}(x,t)$,  $P_{ij}(x,t)$, $l_{ij}(x,t)$, and $k_{ij}(x,t)$ (pp. 120, 123-124).

The general expression for a genotype's relative fitness, $w_{ij}$, is
$$w_{ij} = \sum_x \frac{B(t-x)}{B(t)} k_{ij}(x,t),$$
where $B(t)$ is the number of births in year $t$ (p. 131, eq. 3.24).
If the environment is constant and the population has reached genetic equilibrium and stable age structure, then the ratio of births can be replaced by $\lambda_1^x$ (p. 134).

If the environment is fluctuating, then the only general condition under which the system might reach genetic equilibrium is if the relative performances of the genotypes are independent of age and time:
$$k_{ij}(x,t) = w_{ij}' k_s(x,t),$$
where $k_s(x,t)$ is the demography of a reference genotypes and $w_{ij}'$ is a constant the characterizes the performance of genotype $ij$ relative to the reference genotype (p. 132, eq. 3.25).

Charlesworth goes on to say that this condition is unlikely to be satisfied:

> If selection acts at the level of age-specific survival probabilities, for example, and if genotypic differences in these are indpendent of age, we can write
$$l_{ij}(x) = P_{ij}^x l_s(x)$$
where $l_s(x)$ is the survival function for the genotype with the highest survival probabilities, and $P_{ij} \leq 1$ is a constant characteristic of $A_i A_j$. Even in this simple case, equation (3.25) is violated. (p. 132)

**This appears to be the first explicit acknowledgement of the geometric relationship between annual survival and fitness.**

The remainder of the chapter goes through various examples, mostly theoretical. 
With one exception, the exposition is in terms of $w_{ij}$ and $k_{ij}$, ignoring the contrasting influences of survival and reproduction.
The exception is section 3.4.1 ("Factors influencing reproductive fitness"), which looks explicitly at $l_{ij}(x)$ and $m_{ij}(x)$.
However, Charlesworth proceeds by rather qualititative arguments about how changes in the stable age distribution (this is for a time-invarient model) will tend to favor genotypes with relatively high $k_{ij}(x)$ at smaller or larger values of $x$.
Explicit analysis of cumulative survivorship and maternity schedules is limited to the effects they may have on the shape of the stable age distribution.

One note: Charlesworth does have a section (3.3.3) laying out the conditions for a polymorphic equilibrium under heterozygote advantage. But it is only expressed in terms of $w_{ij}$ and $k_{ij}$.

# Selection dynamics (Chapter 4)
Nearly the entire chapter is expressed in terms of $w_{ij}$ and $k_{ij}$.
$l$ and $m$ make a brief appearance in section 4.3.4, where they are used to derive the probability generating function for the number of $ij$ offspring produced by an $ij$ parent when one of the alleles is rare.
