---
title: "Definitions"
author: "Bruce Kendall"
date: "July 14, 2016"
output:
  pdf_document: default
  html_document: default
---

# Dynamic and static traits
Vindenes & Langangen (2015) classify "traits" as "dynamic" and "static". They do not explicilty define "trait" but seem to use it refer to characteristics (mostly measurable) that affect fitness

- Dynamic traits "are changing over the lifetime, randomly or non-randomly": 
    - age, size, stage, spatial location (mobile organism), body condition, social status

- Static traits "remain the same over the lifetime of an individual, or represent events that occur only once and have a lasting impact on the individual life history.": 
    - Initial size, natal habitat, personality, genotype, sex, natal habitat/environment, birth date, spatial location (sessile organism), habitat

Notes:

- The listed dynamic traits are what we commonly think about as "state"
- "Habitat" need not be static
- In the context of thinking about traits as being autocorrelated within an individual, a static trait is just one with $\rho = 1$.

V&L use the term "individual heterogeneity" to refer to population that is structured by *either* dynamic or static traits. (p. 423)

# Individual stochasticity
Caswell (2009) coined the term "individual stochasticity" to describe the following process (pp. 1763-4):

> Consider a newborn individual. As it develops through the stages of its life cycle, it may grow, shrink, mature, move, reproduce, and allocate resources among its biological processes. At each moment, it is exposed to various mortality risks. Because these processes are stochastic, the lives of any two individuals may differ. These random differences (which I propose to call individual stochasticity) imply that the age-specific properties of an individual (say, longevity) are random variables---there is a distribution among individuals that should be characterized by its mean, moments, etc.

Caswell explicitly distinguishes this from heterogeneity (p. 1779):

> Individual stochasticity must be distinguished from individual heterogeneity, which results from differences among individuals in their inherent properties (e.g. frailty). Heterogeneity has important consequences for demography (Vaupel et al. 1979, Vaupel and Yashin 1985, Vaupel and Carey 1993) and evolution (where it determines the opportunity for selection). However, simply documenting inter-individual variance does not demonstrate the existence of heterogeneity. A standard of comparison is needed, and the calculation of individual stochasticity provides such a standard (Tuljapurkar et al. 2009).

Indeed, he proposes it as a null model for studies of heterogeneity (p. 1770):

> it [variation due to individual stochasticity] can provide a null model for studies of heterogeneity in quantities such as the number of reproductive events. This idea has been explored independently, and in more detail, by Tuljapurkar et al. (2009).

Caswell provides clever computational approaches to calculating moments of various life-history statistics using the theory of absorbing Markov chains; this is further extended in Caswell (2011) by using the theory of Markov chains with rewards.

Notes:

- These results are strictly true for Markov processes, and so apply to standard stage/size-structured matrix models. But when applied to real systems, we have to ask whether the Markov assumption, with its exponential distribution of stage duration, is appropriate. If not, then the amount of variability induced by this process will likely be less (de Valpine et al. 2014)
- I think that the analyses depend on the U matrix being irreducible (sort of; i.e., it's ok not to be able to become a juvenile again, but a juvenile should be able to reach all adult states) (need to check this, actually. there's nothing fundamental in the calculations that seems to preclude this). This would preclude application to a situation where the first transition involves movement into a fixed heterogeneity class (e.g., red vs. blue). But if there was the opportunity (however small) to change classes then this heterogeneity would simply be sucked into "individual stochasticity"

# Dynamic and fixed heterogeneity
Tuljapurkar et al. (2009) define the following for stage-structured Morkov models (pp. 93-4):

- *Dynamic heterogeneity*: "life-history differences among individuals that are generated by the stochastic process that describes changes in stage"
- *Fixed heterogeneity*: "differences between individuals that are fixed at birth"

This is motivated by work in multi-stratum CMR models, in which fixed heterogeneity is estimated/identified using random effect terms.

They work with a $\Psi$ matrix that gives the transition rates conditional on survival. Note that this is written "sideways": it is the transpose of the related component of Caswell's **U** matrix.

The "amount" of demographic heterogenity is described by an entropy, which assesses the diversity of possible life-history trajectories, weighted by their probability of occuring. 

They also define a "persistence" which gives a measure of how long an individual is likely to remain in a given stage, averaged over all stages.

They develop formulas for the mean and variance of time of death and of LRS. The variances are decomposed into within-trajectory (i.e., demographic stochasticity) and among-trajectory contributions.

Notes:

- Fixed heterogeneity here seems to map well to variation in a static trait sensu V & L
- The "trait" over which dynamic heterogeneity is being assessed is an individual's entire life history trajectory, rather than something that can be measured at any given time. It does not appear that the entropy takes survival into account, so only the most long-lived individuals would express the "trait" being measured here.
- Persistence may be a useful way to characterize autocorrelation in V&L's dynamic traits.
- Dynamic heterogeneity is getting at the same general notion as Caswell's individual stochasticity (individuals take different pathways through the transition matrix) but is characterized in a completely different way.
- The decomposition of LRS and lifespan variances are similar in form to Caswell's decomposition into contributions of "stochasticity" and "heterogeneity" for an arbitrary stochastic process with fixed heterogeneity.

# References
- Caswell, H. 2009. Stage, age and individual stochasticity in demography. Oikos 118:1763-1782.
- Caswell, H. 2011. Beyond R0: demographic models for variability of lifetime reproductive output. PLoS ONE 6:e20809.
- de Valpine, P., K. Scranton, J. Knape, K. Ram, and N. J. Mills. 2014. The importance of individual developmental variation in stage-structured population models. Ecology Letters 17:1026-1038.
- Tuljapurkar, S., U. K. Steiner, and S. H. Orzack. 2009. Dynamic heterogeneity in life histories. Ecology Letters 12:93-106.
- Vindenes, Y., and O. Langangen. 2015. Individual heterogeneity in life histories and eco-evolutionary dynamics. Ecology Letters 18:417-432.
