---
title: "Introduction"
author: "Bruce Kendall"
date: "June 25, 2016"
output: 
  html_document: 
    keep_md: yes
---

This is a collection of thoughts and analyses about heterogeneity that might evolve into one ore more papers.

Initial list of topics:

- Synthesize the variety of concepts and definitions in the literature.
- Stochasticity in demography: what is it, and how does it relate to heterogeneity?
- Heterogeneity and stochasticity: How does het affect the total variance in a stochastici process, and how does it affect the instrinsic stochasticity?
- Ontogenetic variation: What are the biological causes (including heterogeneity!), and what are the patterns induced by various "deterministic" model frameworks (DEB, matrix models, IPMs)? A focus here will be on patterns of stage/size at age.
- Markovian ontogenetic models lead to autocorrelations in residual stage/size at age. This age-centric view is essential for understanding the role of cohort selection in shaping the population.
- Autocorrelations only (?) matter (for population growth rate, at least) by creating opportunities for a response to selection. This is why witin-inidividual correlations matter for survival but not reproduction (cohort selection), but parent-offspring correlations matter for both demographic processes (natural selection).
- Correlations across individuals at a given time (e.g., family structure) seems only to affect demographic variance. Relate this to Engen et al's demographic covariance (which might provide a way to introduce correlations into the stochasricity--heterogeneity variance decomposition).  And how do autocorrelations induce within-time correlations (at the very minimum, parent-offspring correlations must induce family structure). 
- What is the role of autocorrelation in ontogenetic trait heterogeneity? Erin's paper is one example of this.
- What is the effect of within-time correlations in ontogenetic trait heterogeneity?


# Potential outline for a synthesis paper

1. Introduction
    - What is heterogeneity
    - Source in traits and environment
    - Effects on process vs. effects on estimation (Vindenes)
    
2. Heterogeneity and stochasticity 

    This is where we get at definitions, including the notion of ontogenetic stochasticity and a trait x environment view of demographic fitness
    
3. How heterogeneity affects stochasticity (the variance decomposition)
4. Intra-individual correlations
5. Inter-generational correlations
6. Inter-individual correlations
